services:
  flask_app:
    build: .
    container_name: flask_api
    restart: always
    environment:
      FLASK_ENV: development
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["python", "app.py"]
    networks:
      - flask_network 
  db:
    image: postgres:15
    container_name: flask_db
    restart: always
    environment:
      POSTGRES_USER: usser
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flask_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - flask_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - flask_network

volumes:
  postgres_data: {}
  grafana_data: {}

networks:
  flask_network:  
    driver: bridge