services:
  flask_app:
    build: .
    container_name: flask_api
    restart: always
    environment:
      FLASK_ENV: development
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["python", "app.py"]
    networks:
      - flask_network 
  db:
    image: postgres:15
    container_name: flask_db
    restart: always
    environment:
      POSTGRES_USER: usser
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flask_network 
volumes:
  postgres_data: {}
networks:
  flask_network:  
    driver: bridge