insert into products (id, name) values (1, 'Beans - Kidney, Red Dry');
insert into products (id, name) values (2, 'Phyllo Dough');
insert into products (id, name) values (3, 'Fruit Mix - Light');
insert into products (id, name) values (4, 'Beef - Tongue, Fresh');
insert into products (id, name) values (5, 'Capon - Breast, Wing On');
insert into products (id, name) values (6, 'Artichokes - Jerusalem');
insert into products (id, name) values (7, 'Chestnuts - Whole,canned');
insert into products (id, name) values (8, 'Remy Red Berry Infusion');
insert into products (id, name) values (9, 'Onions - White');
insert into products (id, name) values (10, 'Ice Cream - Life Savers');
insert into products (id, name) values (11, 'V8 - Tropical Blend');
insert into products (id, name) values (12, 'Wine - Cahors Ac 2000, Clos');
insert into products (id, name) values (13, 'Chocolate - Pistoles, White');
insert into products (id, name) values (14, 'Baking Powder');
insert into products (id, name) values (15, 'Cheese - Shred Cheddar / Mozza');
insert into products (id, name) values (16, 'Pepper - Red Chili');
insert into products (id, name) values (17, 'Slt - Individual Portions');
insert into products (id, name) values (18, 'Syrup - Monin, Amaretta');
insert into products (id, name) values (19, 'Blueberries - Frozen');
insert into products (id, name) values (20, 'Bread - Pullman, Sliced');
insert into products (id, name) values (21, 'Pineapple - Golden');
insert into products (id, name) values (22, 'Wine - Red, Lurton Merlot De');
insert into products (id, name) values (23, 'Soup - Campbells');
insert into products (id, name) values (24, 'Canada Dry');
insert into products (id, name) values (25, 'Mangoes');
insert into products (id, name) values (26, 'Salt - Seasoned');
insert into products (id, name) values (27, 'Soupcontfoam16oz 116con');
insert into products (id, name) values (28, 'Lotus Rootlets - Canned');
insert into products (id, name) values (29, 'Pepper - Green');
insert into products (id, name) values (30, 'Blueberries');
insert into products (id, name) values (31, 'Dragon Fruit');
insert into products (id, name) values (32, 'Rice - Basmati');
insert into products (id, name) values (33, 'Skirt - 24 Foot');
insert into products (id, name) values (34, 'Rum - White, Gg White');
insert into products (id, name) values (35, 'Spice - Montreal Steak Spice');
insert into products (id, name) values (36, 'Hickory Smoke, Liquid');
insert into products (id, name) values (37, 'Beef - Striploin');
insert into products (id, name) values (38, 'Lotus Root');
insert into products (id, name) values (39, 'Bouq All Italian - Primerba');
insert into products (id, name) values (40, 'Coffee - Hazelnut Cream');
insert into products (id, name) values (41, 'Sauce - Chili');
insert into products (id, name) values (42, 'Nantuket Peach Orange');
insert into products (id, name) values (43, 'Lotus Root');
insert into products (id, name) values (44, 'Capers - Ox Eye Daisy');
insert into products (id, name) values (45, 'Gelatine Powder');
insert into products (id, name) values (46, 'Pepper - Gypsy Pepper');
insert into products (id, name) values (47, 'Muffin Mix - Raisin Bran');
insert into products (id, name) values (48, 'Cheese - Parmesan Cubes');
insert into products (id, name) values (49, 'Sauce - Hoisin');
insert into products (id, name) values (50, 'Amarula Cream');
insert into products (id, name) values (51, 'Wiberg Cure');
insert into products (id, name) values (52, 'Venison - Ground');
insert into products (id, name) values (53, 'Cheese - Goat With Herbs');
insert into products (id, name) values (54, 'Vinegar - Raspberry');
insert into products (id, name) values (55, 'Anisette - Mcguiness');
insert into products (id, name) values (56, 'Cheese - Mix');
insert into products (id, name) values (57, 'Coffee Swiss Choc Almond');
insert into products (id, name) values (58, 'Octopus');
insert into products (id, name) values (59, 'Flour - Masa De Harina Mexican');
insert into products (id, name) values (60, 'Lamb Rack Frenched Australian');
insert into products (id, name) values (61, 'Pepper - Paprika, Spanish');
insert into products (id, name) values (62, 'Pepper - Sorrano');
insert into products (id, name) values (63, 'Ezy Change Mophandle');
insert into products (id, name) values (64, 'Veal - Inside');
insert into products (id, name) values (65, 'Chocolate Bar - Smarties');
insert into products (id, name) values (66, 'Ice Cream Bar - Oreo Sandwich');
insert into products (id, name) values (67, 'Puree - Pear');
insert into products (id, name) values (68, 'Wine - Vovray Sec Domaine Huet');
insert into products (id, name) values (69, 'Wine - Chardonnay Mondavi');
insert into products (id, name) values (70, 'Bread Fig And Almond');
insert into products (id, name) values (71, 'Water - San Pellegrino');
insert into products (id, name) values (72, 'Longos - Penne With Pesto');
insert into products (id, name) values (73, 'Wine - Clavet Saint Emilion');
insert into products (id, name) values (74, 'Dasheen');
insert into products (id, name) values (75, 'Plate Foam Laminated 9in Blk');
insert into products (id, name) values (76, 'Longan');
insert into products (id, name) values (77, 'Wiberg Cure');
insert into products (id, name) values (78, 'Wine - Pinot Noir Stoneleigh');
insert into products (id, name) values (79, 'Sorrel - Fresh');
insert into products (id, name) values (80, 'Kippers - Smoked');
insert into products (id, name) values (81, 'Shiratamako - Rice Flour');
insert into products (id, name) values (82, 'Flour - Bran, Red');
insert into products (id, name) values (83, 'Sole - Dover, Whole, Fresh');
insert into products (id, name) values (84, 'Tart Shells - Barquettes, Savory');
insert into products (id, name) values (85, 'Longos - Lasagna Veg');
insert into products (id, name) values (86, 'Flounder - Fresh');
insert into products (id, name) values (87, 'Wine - Sauvignon Blanc');
insert into products (id, name) values (88, 'Bouillion - Fish');
insert into products (id, name) values (89, 'Mangoes');
insert into products (id, name) values (90, 'Flour - So Mix Cake White');
insert into products (id, name) values (91, 'Temperature Recording Station');
insert into products (id, name) values (92, 'Wheat - Soft Kernal Of Wheat');
insert into products (id, name) values (93, 'Spaghetti Squash');
insert into products (id, name) values (94, 'Hinge W Undercut');
insert into products (id, name) values (95, 'Crab - Meat');
insert into products (id, name) values (96, 'Veal - Brisket, Provimi, Bone - In');
insert into products (id, name) values (97, 'Soup - Campbells Pasta Fagioli');
insert into products (id, name) values (98, 'Triple Sec - Mcguinness');
insert into products (id, name) values (99, 'Crawfish');
insert into products (id, name) values (100, 'Potatoes - Purple, Organic');
insert into products (id, name) values (101, 'Veal - Brisket, Provimi,bnls');
insert into products (id, name) values (102, 'Cheese - Grie Des Champ');
insert into products (id, name) values (103, 'Pears - Bosc');
insert into products (id, name) values (104, 'Ecolab - Hobart Washarm End Cap');
insert into products (id, name) values (105, 'Lentils - Green, Dry');
insert into products (id, name) values (106, 'Oranges - Navel, 72');
insert into products (id, name) values (107, 'Marjoram - Dried, Rubbed');
insert into products (id, name) values (108, 'Soup - Campbells - Chicken Noodle');
insert into products (id, name) values (109, 'Flour - Fast / Rapid');
insert into products (id, name) values (110, 'Pasta - Rotini, Colour, Dry');
insert into products (id, name) values (111, 'Veal - Eye Of Round');
insert into products (id, name) values (112, 'Pasta - Lasagne, Fresh');
insert into products (id, name) values (113, 'Cheese - Grana Padano');
insert into products (id, name) values (114, 'Wine - Red, Mouton Cadet');
insert into products (id, name) values (115, 'Bacardi Raspberry');
insert into products (id, name) values (116, 'Pork - Ham Hocks - Smoked');
insert into products (id, name) values (117, 'Sage - Ground');
insert into products (id, name) values (118, 'Red Pepper Paste');
insert into products (id, name) values (119, 'Gatorade - Orange');
insert into products (id, name) values (120, 'Campari');
insert into products (id, name) values (121, 'Veal Inside - Provimi');
insert into products (id, name) values (122, 'Cassis');
insert into products (id, name) values (123, 'Muffin - Banana Nut Individual');
insert into products (id, name) values (124, 'Wine - Pinot Noir Stoneleigh');
insert into products (id, name) values (125, 'Scallops 60/80 Iqf');
insert into products (id, name) values (126, 'Bar Energy Chocchip');
insert into products (id, name) values (127, 'Wine - Chateauneuf Du Pape');
insert into products (id, name) values (128, 'Langers - Cranberry Cocktail');
insert into products (id, name) values (129, 'Wine - Placido Pinot Grigo');
insert into products (id, name) values (130, 'Remy Red');
insert into products (id, name) values (131, 'Pork - Smoked Kassler');
insert into products (id, name) values (132, 'Lettuce - Sea / Sea Asparagus');
insert into products (id, name) values (133, 'Shrimp - Prawn');
insert into products (id, name) values (134, 'Squid - U - 10 Thailand');
insert into products (id, name) values (135, 'Spice - Montreal Steak Spice');
insert into products (id, name) values (136, 'Cheese - Comtomme');
insert into products (id, name) values (137, 'Coffee - Colombian, Portioned');
insert into products (id, name) values (138, 'Steel Wool');
insert into products (id, name) values (139, 'Scallops 60/80 Iqf');
insert into products (id, name) values (140, 'Dawn Professionl Pot And Pan');
insert into products (id, name) values (141, 'Artichokes - Knobless, White');
insert into products (id, name) values (142, 'Macaroons - Homestyle Two Bit');
insert into products (id, name) values (143, 'Wine - Pinot Noir Latour');
insert into products (id, name) values (144, 'Oil - Shortening,liqud, Fry');
insert into products (id, name) values (145, 'Pickles - Gherkins');
insert into products (id, name) values (146, 'Broccoli - Fresh');
insert into products (id, name) values (147, 'Lamb - Leg, Diced');
insert into products (id, name) values (148, 'Chickensplit Half');
insert into products (id, name) values (149, 'Tomatoes - Vine Ripe, Red');
insert into products (id, name) values (150, 'Appetizer - Escargot Puff');
insert into products (id, name) values (151, 'Cake - Sheet Strawberry');
insert into products (id, name) values (152, 'Sugar - Individual Portions');
insert into products (id, name) values (153, 'Yoghurt Tubes');
insert into products (id, name) values (154, 'Bread - Olive');
insert into products (id, name) values (155, 'Bar Mix - Lime');
insert into products (id, name) values (156, 'Cake - Mini Potato Pancake');
insert into products (id, name) values (157, 'Mini - Vol Au Vents');
insert into products (id, name) values (158, 'Chocolate Eclairs');
insert into products (id, name) values (159, 'Stock - Fish');
insert into products (id, name) values (160, 'Carrots - Mini, Stem On');
insert into products (id, name) values (161, 'Sauce - White, Mix');
insert into products (id, name) values (162, 'Veal - Nuckle');
insert into products (id, name) values (163, 'Vinegar - White');
insert into products (id, name) values (164, 'Cheese - Brie Roitelet');
insert into products (id, name) values (165, 'Bread - Multigrain, Loaf');
insert into products (id, name) values (166, 'Nut - Cashews, Whole, Raw');
insert into products (id, name) values (167, 'Dragon Fruit');
insert into products (id, name) values (168, 'Iced Tea - Lemon, 340ml');
insert into products (id, name) values (169, 'Pepper - Jalapeno');
insert into products (id, name) values (170, 'Potatoes - Idaho 100 Count');
insert into products (id, name) values (171, 'Triple Sec - Mcguinness');
insert into products (id, name) values (172, 'Wine - Touraine Azay - Le - Rideau');
insert into products (id, name) values (173, 'Spinach - Baby');
insert into products (id, name) values (174, 'Spinach - Packaged');
insert into products (id, name) values (175, 'Soup - Cream Of Broccoli');
insert into products (id, name) values (176, 'Pork - Chop, Frenched');
insert into products (id, name) values (177, 'Lamb - Loin, Trimmed, Boneless');
insert into products (id, name) values (178, 'Daikon Radish');
insert into products (id, name) values (179, 'Beef - Cooked, Corned');
insert into products (id, name) values (180, 'Nantucket - 518ml');
insert into products (id, name) values (181, 'Samosa - Veg');
insert into products (id, name) values (182, 'Pail For Lid 1537');
insert into products (id, name) values (183, 'Wine - Rhine Riesling Wolf Blass');
insert into products (id, name) values (184, 'Table Cloth 62x120 White');
insert into products (id, name) values (185, 'Cleaner - Comet');
insert into products (id, name) values (186, 'Croissants Thaw And Serve');
insert into products (id, name) values (187, 'Blouse / Shirt / Sweater');
insert into products (id, name) values (188, 'Wine - Manischewitz Concord');
insert into products (id, name) values (189, 'Nantucket - Kiwi Berry Cktl.');
insert into products (id, name) values (190, 'Beer - True North Lager');
insert into products (id, name) values (191, 'Plate - Foam, Bread And Butter');
insert into products (id, name) values (192, 'Wine - Rosso Toscano Igt');
insert into products (id, name) values (193, 'Artichokes - Knobless, White');
insert into products (id, name) values (194, 'Paper - Brown Paper Mini Cups');
insert into products (id, name) values (195, 'Oil - Peanut');
insert into products (id, name) values (196, 'Capon - Breast, Wing On');
insert into products (id, name) values (197, 'Pork - Backs - Boneless');
insert into products (id, name) values (198, 'Buffalo - Striploin');
insert into products (id, name) values (199, 'Island Oasis - Raspberry');
insert into products (id, name) values (200, 'Wine - Magnotta - Bel Paese White');
insert into products (id, name) values (201, 'Pickerel - Fillets');
insert into products (id, name) values (202, 'Vinegar - Tarragon');
insert into products (id, name) values (203, 'Longos - Lasagna Veg');
insert into products (id, name) values (204, 'Sun - Dried Tomatoes');
insert into products (id, name) values (205, 'Extract Vanilla Pure');
insert into products (id, name) values (206, 'Pastry - Butterscotch Baked');
insert into products (id, name) values (207, 'Shrimp - 16/20, Peeled Deviened');
insert into products (id, name) values (208, 'Sterno - Chafing Dish Fuel');
insert into products (id, name) values (209, 'Shrimp - 100 / 200 Cold Water');
insert into products (id, name) values (210, 'Chicken - Bones');
insert into products (id, name) values (211, 'Ice Cream - Chocolate');
insert into products (id, name) values (212, 'Guinea Fowl');
insert into products (id, name) values (213, 'Chocolate - Milk');
insert into products (id, name) values (214, 'Crab - Blue, Frozen');
insert into products (id, name) values (215, 'Parsnip');
insert into products (id, name) values (216, 'Pepsi - Diet, 355 Ml');
insert into products (id, name) values (217, 'Bouillion - Fish');
insert into products (id, name) values (218, 'Mushroom - Portebello');
insert into products (id, name) values (219, 'Wine - Chateauneuf Du Pape');
insert into products (id, name) values (220, 'Sugar - Cubes');
insert into products (id, name) values (221, 'Beef - Striploin Aa');
insert into products (id, name) values (222, 'Pepper - Cayenne');
insert into products (id, name) values (223, 'Beans - Black Bean, Preserved');
insert into products (id, name) values (224, 'Foie Gras');
insert into products (id, name) values (225, 'Wine - Rubyport');
insert into products (id, name) values (226, 'Bay Leaf Ground');
insert into products (id, name) values (227, 'Soup - Campbells Broccoli');
insert into products (id, name) values (228, 'Pasta - Canelloni, Single Serve');
insert into products (id, name) values (229, 'Garlic - Primerba, Paste');
insert into products (id, name) values (230, 'Ostrich - Prime Cut');
insert into products (id, name) values (231, 'Sauce - Chili');
insert into products (id, name) values (232, 'Chick Peas - Dried');
insert into products (id, name) values (233, 'Pea - Snow');
insert into products (id, name) values (234, 'Beef - Top Butt Aaa');
insert into products (id, name) values (235, 'Bread - Hot Dog Buns');
insert into products (id, name) values (236, 'Truffle Cups - White Paper');
insert into products (id, name) values (237, 'Shrimp - Prawn');
insert into products (id, name) values (238, 'Soup - Campbells Beef Strogonoff');
insert into products (id, name) values (239, 'Kumquat');
insert into products (id, name) values (240, 'Soup V8 Roasted Red Pepper');
insert into products (id, name) values (241, 'Remy Red Berry Infusion');
insert into products (id, name) values (242, 'Seedlings - Mix, Organic');
insert into products (id, name) values (243, 'Dates');
insert into products (id, name) values (244, 'Syrup - Monin - Passion Fruit');
insert into products (id, name) values (245, 'Cheese - Colby');
insert into products (id, name) values (246, 'Vermouth - White, Cinzano');
insert into products (id, name) values (247, 'Compound - Orange');
insert into products (id, name) values (248, 'Jicama');
insert into products (id, name) values (249, 'Juice - Pineapple, 341 Ml');
insert into products (id, name) values (250, 'Squid Ink');
insert into products (id, name) values (251, 'Chocolate - Dark');
insert into products (id, name) values (252, 'Nut - Hazelnut, Ground, Natural');
insert into products (id, name) values (253, 'Cake - Night And Day Choclate');
insert into products (id, name) values (254, 'Star Fruit');
insert into products (id, name) values (255, 'Tea - Herbal I Love Lemon');
insert into products (id, name) values (256, 'V8 - Tropical Blend');
insert into products (id, name) values (257, 'Muffin Mix - Banana Nut');
insert into products (id, name) values (258, 'Mushroom - Trumpet, Dry');
insert into products (id, name) values (259, 'Sambuca - Ramazzotti');
insert into products (id, name) values (260, 'Rice Wine - Aji Mirin');
insert into products (id, name) values (261, 'Butter - Unsalted');
insert into products (id, name) values (262, 'Tomatoes - Heirloom');
insert into products (id, name) values (263, 'Pork Salted Bellies');
insert into products (id, name) values (264, 'Squeeze Bottle');
insert into products (id, name) values (265, 'French Pastry - Mini Chocolate');
insert into products (id, name) values (266, 'Wine - Ruffino Chianti Classico');
insert into products (id, name) values (267, 'Veal - Bones');
insert into products (id, name) values (268, 'Bread Roll Foccacia');
insert into products (id, name) values (269, 'Aspic - Clear');
insert into products (id, name) values (270, 'Island Oasis - Raspberry');
insert into products (id, name) values (271, 'Tortillas - Flour, 8');
insert into products (id, name) values (272, 'Pail - 15l White, With Handle');
insert into products (id, name) values (273, 'Coffee - Decaffeinato Coffee');
insert into products (id, name) values (274, 'Sponge Cake Mix - Chocolate');
insert into products (id, name) values (275, 'Turkey - Breast, Double');
insert into products (id, name) values (276, 'Pork - Sausage Casing');
insert into products (id, name) values (277, 'Soup - Campbells, Beef Barley');
insert into products (id, name) values (278, 'Chick Peas - Dried');
insert into products (id, name) values (279, 'Mangoes');
insert into products (id, name) values (280, 'Dried Figs');
insert into products (id, name) values (281, 'Tomatoes - Diced, Canned');
insert into products (id, name) values (282, 'Pork - Back, Long Cut, Boneless');
insert into products (id, name) values (283, 'Ginger - Ground');
insert into products (id, name) values (284, 'Lamb - Shanks');
insert into products (id, name) values (285, 'Dc - Sakura Fu');
insert into products (id, name) values (286, 'Vinegar - Champagne');
insert into products (id, name) values (287, 'Country Roll');
insert into products (id, name) values (288, 'Foam Cup 6 Oz');
insert into products (id, name) values (289, 'Muffin - Banana Nut Individual');
insert into products (id, name) values (290, 'Apricots - Dried');
insert into products (id, name) values (291, 'Mikes Hard Lemonade');
insert into products (id, name) values (292, 'Orange Roughy 6/8 Oz');
insert into products (id, name) values (293, 'Wine - Champagne Brut Veuve');
insert into products (id, name) values (294, 'Crab Meat Claw Pasteurise');
insert into products (id, name) values (295, 'Aspic - Light');
insert into products (id, name) values (296, 'Nantucket - 518ml');
insert into products (id, name) values (297, 'Huck White Towels');
insert into products (id, name) values (298, 'Wine - Magnotta - Pinot Gris Sr');
insert into products (id, name) values (299, 'Melon - Honey Dew');
insert into products (id, name) values (300, 'Ostrich - Prime Cut');
insert into products (id, name) values (301, 'Beer - Upper Canada Light');
insert into products (id, name) values (302, 'Wood Chips - Regular');
insert into products (id, name) values (303, 'Dome Lid Clear P92008h');
insert into products (id, name) values (304, 'Fish - Bones');
insert into products (id, name) values (305, 'Long Island Ice Tea');
insert into products (id, name) values (306, 'Pepper - Cubanelle');
insert into products (id, name) values (307, 'Cake Circle, Paprus');
insert into products (id, name) values (308, 'Beef - Bresaola');
insert into products (id, name) values (309, 'Pork - Back, Short Cut, Boneless');
insert into products (id, name) values (310, 'Soup - Campbells Broccoli');
insert into products (id, name) values (311, 'Oranges - Navel, 72');
insert into products (id, name) values (312, 'Vinegar - Champagne');
insert into products (id, name) values (313, 'Ice Cream - Super Sandwich');
insert into products (id, name) values (314, 'Crackers - Melba Toast');
insert into products (id, name) values (315, 'Wine - Dubouef Macon - Villages');
insert into products (id, name) values (316, 'Chinese Foods - Chicken');
insert into products (id, name) values (317, 'Brocolinni - Gaylan, Chinese');
insert into products (id, name) values (318, 'Food Colouring - Green');
insert into products (id, name) values (319, 'Anchovy In Oil');
insert into products (id, name) values (320, 'Split Peas - Yellow, Dry');
insert into products (id, name) values (321, 'Shrimp - Black Tiger 16/20');
insert into products (id, name) values (322, 'Cocoa Butter');
insert into products (id, name) values (323, 'Beef - Ox Tongue, Pickled');
insert into products (id, name) values (324, 'Coffee - Decaffeinato Coffee');
insert into products (id, name) values (325, 'Oil - Shortening,liqud, Fry');
insert into products (id, name) values (326, 'Wine - Port Late Bottled Vintage');
insert into products (id, name) values (327, 'Shallots');
insert into products (id, name) values (328, 'Goat - Leg');
insert into products (id, name) values (329, 'Pasta - Ravioli');
insert into products (id, name) values (330, 'Fennel - Seeds');
insert into products (id, name) values (331, 'Chick Peas - Canned');
insert into products (id, name) values (332, 'Soup - Beef Conomme, Dry');
insert into products (id, name) values (333, 'Pastry - Mini French Pastries');
insert into products (id, name) values (334, 'Pasta - Angel Hair');
insert into products (id, name) values (335, 'Anisette - Mcguiness');
insert into products (id, name) values (336, 'Crackers - Soda / Saltins');
insert into products (id, name) values (337, 'Red Snapper - Fillet, Skin On');
insert into products (id, name) values (338, 'Carbonated Water - Raspberry');
insert into products (id, name) values (339, 'Wine - Chateau Bonnet');
insert into products (id, name) values (340, 'Plastic Arrow Stir Stick');
insert into products (id, name) values (341, 'Soup V8 Roasted Red Pepper');
insert into products (id, name) values (342, 'Amarula Cream');
insert into products (id, name) values (343, 'Bar - Granola Trail Mix Fruit Nut');
insert into products (id, name) values (344, 'Chocolate Bar - Reese Pieces');
insert into products (id, name) values (345, 'Cream Of Tartar');
insert into products (id, name) values (346, 'Bread - Multigrain');
insert into products (id, name) values (347, 'Melon - Cantaloupe');
insert into products (id, name) values (348, 'Soup - Campbells, Creamy');
insert into products (id, name) values (349, 'Nantucket Cranberry Juice');
insert into products (id, name) values (350, 'Juice Peach Nectar');
insert into products (id, name) values (351, 'Poppy Seed');
insert into products (id, name) values (352, 'Wine - Fontanafredda Barolo');
insert into products (id, name) values (353, 'Pepper - Chipotle, Canned');
insert into products (id, name) values (354, 'Chicken - Wieners');
insert into products (id, name) values (355, 'Venison - Striploin');
insert into products (id, name) values (356, 'Mushroom - Trumpet, Dry');
insert into products (id, name) values (357, 'Chilli Paste, Ginger Garlic');
insert into products (id, name) values (358, 'Cherries - Fresh');
insert into products (id, name) values (359, 'Poppy Seed');
insert into products (id, name) values (360, 'Lemon Tarts');
insert into products (id, name) values (361, 'Fennel');
insert into products (id, name) values (362, 'Sauce - Cranberry');
insert into products (id, name) values (363, 'Pasta - Spaghetti, Dry');
insert into products (id, name) values (364, 'Tomatoes - Diced, Canned');
insert into products (id, name) values (365, 'Soup Knorr Chili With Beans');
insert into products (id, name) values (366, 'Bread - White Epi Baguette');
insert into products (id, name) values (367, 'Miso Paste White');
insert into products (id, name) values (368, 'Cabbage Roll');
insert into products (id, name) values (369, 'Poppy Seed');
insert into products (id, name) values (370, 'Grapes - Red');
insert into products (id, name) values (371, 'Capon - Whole');
insert into products (id, name) values (372, 'Chocolate - Dark Callets');
insert into products (id, name) values (373, 'Sausage - Breakfast');
insert into products (id, name) values (374, 'Sauce - Ranch Dressing');
insert into products (id, name) values (375, 'Salt - Celery');
insert into products (id, name) values (376, 'Otomegusa Dashi Konbu');
insert into products (id, name) values (377, 'Cabbage Roll');
insert into products (id, name) values (378, 'Shark - Loin');
insert into products (id, name) values (379, 'Soup - Campbells Chicken');
insert into products (id, name) values (380, 'Chicken - Soup Base');
insert into products (id, name) values (381, 'Buffalo - Short Rib Fresh');
insert into products (id, name) values (382, 'Brocolinni - Gaylan, Chinese');
insert into products (id, name) values (383, 'Piping Jelly - All Colours');
insert into products (id, name) values (384, 'Herb Du Provence - Primerba');
insert into products (id, name) values (385, 'Bread - Dark Rye, Loaf');
insert into products (id, name) values (386, 'Stock - Veal, Brown');
insert into products (id, name) values (387, 'Sage - Ground');
insert into products (id, name) values (388, 'Chicken - White Meat, No Tender');
insert into products (id, name) values (389, 'Wine - Ej Gallo Sonoma');
insert into products (id, name) values (390, 'Bread Crumbs - Panko');
insert into products (id, name) values (391, 'Versatainer Nc - 888');
insert into products (id, name) values (392, 'Pastry - Plain Baked Croissant');
insert into products (id, name) values (393, 'Olives - Green, Pitted');
insert into products (id, name) values (394, 'Juice - Orangina');
insert into products (id, name) values (395, 'Kolrabi');
insert into products (id, name) values (396, 'Corn - Mini');
insert into products (id, name) values (397, 'Sprouts - Onion');
insert into products (id, name) values (398, 'Asparagus - White, Canned');
insert into products (id, name) values (399, 'Apron');
insert into products (id, name) values (400, 'Beer - Guiness');
insert into products (id, name) values (401, 'Cheese - Bakers Cream Cheese');
insert into products (id, name) values (402, 'Lamb - Loin Chops');
insert into products (id, name) values (403, 'Soup - Campbells Pasta Fagioli');
insert into products (id, name) values (404, 'Nut - Cashews, Whole, Raw');
insert into products (id, name) values (405, 'Cake - Night And Day Choclate');
insert into products (id, name) values (406, 'Sugar Thermometer');
insert into products (id, name) values (407, 'Cookies Oatmeal Raisin');
insert into products (id, name) values (408, 'Wine - Fino Tio Pepe Gonzalez');
insert into products (id, name) values (409, 'Pepsi, 355 Ml');
insert into products (id, name) values (410, 'Flower - Commercial Bronze');
insert into products (id, name) values (411, 'Currants');
insert into products (id, name) values (412, 'Spic And Span All Purpose');
insert into products (id, name) values (413, 'Chinese Foods - Plain Fried Rice');
insert into products (id, name) values (414, 'Pasta - Canelloni');
insert into products (id, name) values (415, 'Melon - Watermelon Yellow');
insert into products (id, name) values (416, 'Wine - White, Pinot Grigio');
insert into products (id, name) values (417, 'Cheese - Comtomme');
insert into products (id, name) values (418, 'Wine - Vouvray Cuvee Domaine');
insert into products (id, name) values (419, 'Steel Wool S.o.s');
insert into products (id, name) values (420, 'Vinegar - Red Wine');
insert into products (id, name) values (421, 'Lettuce - Curly Endive');
insert into products (id, name) values (422, 'Dome Lid Clear P92008h');
insert into products (id, name) values (423, 'Mustard - Dijon');
insert into products (id, name) values (424, 'Cheese Cheddar Processed');
insert into products (id, name) values (425, 'Lamb - Loin, Trimmed, Boneless');
insert into products (id, name) values (426, 'Cloves - Ground');
insert into products (id, name) values (427, 'Milk 2% 500 Ml');
insert into products (id, name) values (428, 'Cheese Cloth');
insert into products (id, name) values (429, 'Juice - V8, Tomato');
insert into products (id, name) values (430, 'Wine - Chianti Classica Docg');
insert into products (id, name) values (431, 'Leeks - Large');
insert into products (id, name) values (432, 'Plums - Red');
insert into products (id, name) values (433, 'Soup Knorr Chili With Beans');
insert into products (id, name) values (434, 'Icecream - Dibs');
insert into products (id, name) values (435, 'Fiddlehead - Frozen');
insert into products (id, name) values (436, 'Garam Marsala');
insert into products (id, name) values (437, 'Browning Caramel Glace');
insert into products (id, name) values (438, 'Bread - Focaccia Quarter');
insert into products (id, name) values (439, 'Vinegar - Rice');
insert into products (id, name) values (440, 'Halibut - Steaks');
insert into products (id, name) values (441, 'Syrup - Monin, Swiss Choclate');
insert into products (id, name) values (442, 'Juice - Orange, Concentrate');
insert into products (id, name) values (443, 'Tea - Honey Green Tea');
insert into products (id, name) values (444, 'Oil - Truffle, White');
insert into products (id, name) values (445, 'Onions - Pearl');
insert into products (id, name) values (446, 'Kahlua');
insert into products (id, name) values (447, 'Basil - Fresh');
insert into products (id, name) values (448, 'Wine - Zinfandel Rosenblum');
insert into products (id, name) values (449, 'Potatoes - Peeled');
insert into products (id, name) values (450, 'Rice - 7 Grain Blend');
insert into products (id, name) values (451, 'Lamb - Whole Head Off,nz');
insert into products (id, name) values (452, 'Clams - Littleneck, Whole');
insert into products (id, name) values (453, 'Chicken - Soup Base');
insert into products (id, name) values (454, 'Stock - Veal, Brown');
insert into products (id, name) values (455, 'Wine - Rosso Toscano Igt');
insert into products (id, name) values (456, 'Beef - Bresaola');
insert into products (id, name) values (457, 'Coffee - Flavoured');
insert into products (id, name) values (458, 'Chocolate Bar - Oh Henry');
insert into products (id, name) values (459, 'Beef - Eye Of Round');
insert into products (id, name) values (460, 'Icecream - Dstk Strw Chseck');
insert into products (id, name) values (461, 'Cookies - Fortune');
insert into products (id, name) values (462, 'Food Colouring - Green');
insert into products (id, name) values (463, 'Fireball Whisky');
insert into products (id, name) values (464, 'Yogurt - Cherry, 175 Gr');
insert into products (id, name) values (465, 'Chocolate - Pistoles, Lactee, Milk');
insert into products (id, name) values (466, 'Sage - Rubbed');
insert into products (id, name) values (467, 'Cookies Oatmeal Raisin');
insert into products (id, name) values (468, 'Nantuket Peach Orange');
insert into products (id, name) values (469, 'Lid Tray - 16in Dome');
insert into products (id, name) values (470, 'Wine - Placido Pinot Grigo');
insert into products (id, name) values (471, 'Apples - Sliced / Wedge');
insert into products (id, name) values (472, 'Wine - Rubyport');
insert into products (id, name) values (473, 'Salt And Pepper Mix - Black');
insert into products (id, name) values (474, 'Lettuce - Romaine');
insert into products (id, name) values (475, 'Coffee - Egg Nog Capuccino');
insert into products (id, name) values (476, 'Sauce - Mint');
insert into products (id, name) values (477, 'Longos - Grilled Veg Sandwiches');
insert into products (id, name) values (478, 'Potato - Sweet');
insert into products (id, name) values (479, 'Sauce - Salsa');
insert into products (id, name) values (480, 'Avocado');
insert into products (id, name) values (481, 'Evaporated Milk - Skim');
insert into products (id, name) values (482, 'Nut - Almond, Blanched, Sliced');
insert into products (id, name) values (483, 'Bagelers - Cinn / Brown Sugar');
insert into products (id, name) values (484, 'Guava');
insert into products (id, name) values (485, 'Yogurt - Banana, 175 Gr');
insert into products (id, name) values (486, 'Wine - Red, Gallo, Merlot');
insert into products (id, name) values (487, 'Bandage - Fexible 1x3');
insert into products (id, name) values (488, 'Coffee - French Vanilla Frothy');
insert into products (id, name) values (489, 'Cheese - Taleggio D.o.p.');
insert into products (id, name) values (490, 'Soup - Campbells Mac N Cheese');
insert into products (id, name) values (491, 'Ice Cream Bar - Oreo Cone');
insert into products (id, name) values (492, 'Wine - Fontanafredda Barolo');
insert into products (id, name) values (493, 'Apple - Custard');
insert into products (id, name) values (494, 'Cookies - Fortune');
insert into products (id, name) values (495, 'Water - Tonic');
insert into products (id, name) values (496, 'Hickory Smoke, Liquid');
insert into products (id, name) values (497, 'Butter - Salted, Micro');
insert into products (id, name) values (498, 'Straws - Cocktale');
insert into products (id, name) values (499, 'Red Cod Fillets - 225g');
insert into products (id, name) values (500, 'Lamb - Whole, Frozen');
insert into products (id, name) values (501, 'Beans - Kidney White');
insert into products (id, name) values (502, 'Tart Shells - Sweet, 2');
insert into products (id, name) values (503, 'Nantucket - Pomegranate Pear');
insert into products (id, name) values (504, 'Chocolate Bar - Smarties');
insert into products (id, name) values (505, 'Veal - Insides, Grains');
insert into products (id, name) values (506, 'Wonton Wrappers');
insert into products (id, name) values (507, 'Food Colouring - Green');
insert into products (id, name) values (508, 'Table Cloth 90x90 White');
insert into products (id, name) values (509, 'Lamb - Whole Head Off,nz');
insert into products (id, name) values (510, 'Brocolinni - Gaylan, Chinese');
insert into products (id, name) values (511, 'Cake - Box Window 10x10x2.5');
insert into products (id, name) values (512, 'Pie Filling - Cherry');
insert into products (id, name) values (513, 'Vodka - Lemon, Absolut');
insert into products (id, name) values (514, 'Sugar - Sweet N Low, Individual');
insert into products (id, name) values (515, 'Appetizer - Tarragon Chicken');
insert into products (id, name) values (516, 'Icecream Bar - Del Monte');
insert into products (id, name) values (517, 'Lettuce - Green Leaf');
insert into products (id, name) values (518, 'Dasheen');
insert into products (id, name) values (519, 'Cucumber - Pickling Ontario');
insert into products (id, name) values (520, 'Potatoes - Mini White 3 Oz');
insert into products (id, name) values (521, 'Honey - Liquid');
insert into products (id, name) values (522, 'Pasta - Spaghetti, Dry');
insert into products (id, name) values (523, 'Tomatoes Tear Drop Yellow');
insert into products (id, name) values (524, 'Squid - Breaded');
insert into products (id, name) values (525, 'Rum - White, Gg White');
insert into products (id, name) values (526, 'Cabbage - Savoy');
insert into products (id, name) values (527, 'Carbonated Water - Peach');
insert into products (id, name) values (528, 'Pop - Club Soda Can');
insert into products (id, name) values (529, 'Asparagus - Frozen');
insert into products (id, name) values (530, 'Crab - Claws, 26 - 30');
insert into products (id, name) values (531, 'White Fish - Filets');
insert into products (id, name) values (532, 'Maintenance Removal Charge');
insert into products (id, name) values (533, 'Wine - Red, Colio Cabernet');
insert into products (id, name) values (534, 'Pate - Cognac');
insert into products (id, name) values (535, 'Lamb - Shanks');
insert into products (id, name) values (536, 'Milk - 2% 250 Ml');
insert into products (id, name) values (537, 'Tart Shells - Savory, 4');
insert into products (id, name) values (538, 'Bread - White Mini Epi');
insert into products (id, name) values (539, 'Milk - 1%');
insert into products (id, name) values (540, 'Bananas');
insert into products (id, name) values (541, 'Quail - Jumbo');
insert into products (id, name) values (542, 'Fudge - Chocolate Fudge');
insert into products (id, name) values (543, 'Bread Sour Rolls');
insert into products (id, name) values (544, 'Star Anise, Whole');
insert into products (id, name) values (545, 'Steampan - Foil');
insert into products (id, name) values (546, 'Wine - White, Lindemans Bin 95');
insert into products (id, name) values (547, 'Chips Potato All Dressed - 43g');
insert into products (id, name) values (548, 'Pop - Club Soda Can');
insert into products (id, name) values (549, 'Easy Off Oven Cleaner');
insert into products (id, name) values (550, 'Hinge W Undercut');
insert into products (id, name) values (551, 'Barley - Pearl');
insert into products (id, name) values (552, 'Beef - Tender Tips');
insert into products (id, name) values (553, 'Scallops - 20/30');
insert into products (id, name) values (554, 'Bread Crumbs - Japanese Style');
insert into products (id, name) values (555, 'Bread - Roll, Canadian Dinner');
insert into products (id, name) values (556, 'Sobe - Lizard Fuel');
insert into products (id, name) values (557, 'Lemon Grass');
insert into products (id, name) values (558, 'Venison - Denver Leg Boneless');
insert into products (id, name) values (559, 'Pastry - Banana Tea Loaf');
insert into products (id, name) values (560, 'Pastry - Butterscotch Baked');
insert into products (id, name) values (561, 'Cauliflower');
insert into products (id, name) values (562, 'Oil - Cooking Spray');
insert into products (id, name) values (563, 'Bag - Clear 7 Lb');
insert into products (id, name) values (564, 'Wine - Alicanca Vinho Verde');
insert into products (id, name) values (565, 'Table Cloth 53x53 White');
insert into products (id, name) values (566, 'Egg Patty Fried');
insert into products (id, name) values (567, 'Tea - Black Currant');
insert into products (id, name) values (568, 'Soup Campbells - Italian Wedding');
insert into products (id, name) values (569, 'Mushroom - Enoki, Dry');
insert into products (id, name) values (570, 'Wine - Soave Folonari');
insert into products (id, name) values (571, 'Syrup - Chocolate');
insert into products (id, name) values (572, 'Tart - Butter Plain Squares');
insert into products (id, name) values (573, 'Bread - Onion Focaccia');
insert into products (id, name) values (574, 'Silicone Paper 16.5x24');
insert into products (id, name) values (575, 'Energy - Boo - Koo');
insert into products (id, name) values (576, 'Ice Cream - Life Savers');
insert into products (id, name) values (577, 'Cookies Almond Hazelnut');
insert into products (id, name) values (578, 'Roe - Lump Fish, Red');
insert into products (id, name) values (579, 'Mortadella');
insert into products (id, name) values (580, 'Oil - Sesame');
insert into products (id, name) values (581, 'Pie Filling - Pumpkin');
insert into products (id, name) values (582, 'Tart Shells - Savory, 2');
insert into products (id, name) values (583, 'Goldschalger');
insert into products (id, name) values (584, 'Wine - Red, Cabernet Sauvignon');
insert into products (id, name) values (585, 'Sprouts - Baby Pea Tendrils');
insert into products (id, name) values (586, 'Pumpkin');
insert into products (id, name) values (587, 'Tea - Herbal Orange Spice');
insert into products (id, name) values (588, 'Skirt - 29 Foot');
insert into products (id, name) values (589, 'Whmis - Spray Bottle Trigger');
insert into products (id, name) values (590, 'Pickerel - Fillets');
insert into products (id, name) values (591, 'Jam - Raspberry');
insert into products (id, name) values (592, 'Sugar - Crumb');
insert into products (id, name) values (593, 'Oil - Pumpkinseed');
insert into products (id, name) values (594, 'Beans - Navy, Dry');
insert into products (id, name) values (595, 'Nut - Almond, Blanched, Sliced');
insert into products (id, name) values (596, 'Vermacelli - Sprinkles, Assorted');
insert into products (id, name) values (597, 'Mushroom - Enoki, Fresh');
insert into products (id, name) values (598, 'Chevril');
insert into products (id, name) values (599, 'Chocolate - Liqueur Cups With Foil');
insert into products (id, name) values (600, 'Bread - Dark Rye, Loaf');
insert into products (id, name) values (601, 'Quail - Eggs, Fresh');
insert into products (id, name) values (602, 'Lamb - Racks, Frenched');
insert into products (id, name) values (603, 'Yeast Dry - Fermipan');
insert into products (id, name) values (604, 'Thyme - Dried');
insert into products (id, name) values (605, 'Chicken - Whole Fryers');
insert into products (id, name) values (606, 'Chinese Foods - Chicken');
insert into products (id, name) values (607, 'Cheese - Sheep Milk');
insert into products (id, name) values (608, 'Carbonated Water - Peach');
insert into products (id, name) values (609, 'Muffin Hinge 117n');
insert into products (id, name) values (610, 'Milk Powder');
insert into products (id, name) values (611, 'Sorrel - Fresh');
insert into products (id, name) values (612, 'Bagel - 12 Grain Preslice');
insert into products (id, name) values (613, 'Wine - Delicato Merlot');
insert into products (id, name) values (614, 'Chicken - Base');
insert into products (id, name) values (615, 'Extract - Vanilla,artificial');
insert into products (id, name) values (616, 'Straw - Regular');
insert into products (id, name) values (617, 'Lamb Shoulder Boneless Nz');
insert into products (id, name) values (618, 'Spinach - Baby');
insert into products (id, name) values (619, 'Jam - Marmalade, Orange');
insert into products (id, name) values (620, 'Cleaner - Comet');
insert into products (id, name) values (621, 'Sparkling Wine - Rose, Freixenet');
insert into products (id, name) values (622, 'Glaze - Apricot');
insert into products (id, name) values (623, 'Soup - Boston Clam Chowder');
insert into products (id, name) values (624, 'Jicama');
insert into products (id, name) values (625, 'Allspice - Jamaican');
insert into products (id, name) values (626, 'Ecolab Crystal Fusion');
insert into products (id, name) values (627, 'Cheese - Mascarpone');
insert into products (id, name) values (628, 'Wine - Lamancha Do Crianza');
insert into products (id, name) values (629, 'Cauliflower');
insert into products (id, name) values (630, 'Wine - Marlbourough Sauv Blanc');
insert into products (id, name) values (631, 'Soup Bowl Clear 8oz92008');
insert into products (id, name) values (632, 'Rice Wine - Aji Mirin');
insert into products (id, name) values (633, 'Pasta - Bauletti, Chicken White');
insert into products (id, name) values (634, 'Cheese - Fontina');
insert into products (id, name) values (635, 'Chips Potato All Dressed - 43g');
insert into products (id, name) values (636, 'Lotus Rootlets - Canned');
insert into products (id, name) values (637, 'Peppercorns - Pink');
insert into products (id, name) values (638, 'Ocean Spray - Kiwi Strawberry');
insert into products (id, name) values (639, 'Pepper Squash');
insert into products (id, name) values (640, 'Puree - Kiwi');
insert into products (id, name) values (641, 'Bacardi Mojito');
insert into products (id, name) values (642, 'Loaf Pan - 2 Lb, Foil');
insert into products (id, name) values (643, 'Vodka - Lemon, Absolut');
insert into products (id, name) values (644, 'Wine - Touraine Azay - Le - Rideau');
insert into products (id, name) values (645, 'Wine - Hardys Bankside Shiraz');
insert into products (id, name) values (646, 'Mushroom - Chantrelle, Fresh');
insert into products (id, name) values (647, 'Foam Cup 6 Oz');
insert into products (id, name) values (648, 'Napkin Colour');
insert into products (id, name) values (649, 'Oysters - Smoked');
insert into products (id, name) values (650, 'Tofu - Firm');
insert into products (id, name) values (651, 'Water - Spring Water, 355 Ml');
insert into products (id, name) values (652, 'Lamb - Loin Chops');
insert into products (id, name) values (653, 'Butter - Unsalted');
insert into products (id, name) values (654, 'Tobasco Sauce');
insert into products (id, name) values (655, 'Tequila - Sauza Silver');
insert into products (id, name) values (656, 'Olive - Spread Tapenade');
insert into products (id, name) values (657, 'Napkin Colour');
insert into products (id, name) values (658, 'Eel - Smoked');
insert into products (id, name) values (659, 'Cake - Lemon Chiffon');
insert into products (id, name) values (660, 'Cheese - Feta');
insert into products (id, name) values (661, 'Tomatoes - Vine Ripe, Red');
insert into products (id, name) values (662, 'Beef - Tongue, Fresh');
insert into products (id, name) values (663, 'Watercress');
insert into products (id, name) values (664, 'Pork - Inside');
insert into products (id, name) values (665, 'Wine - Prem Select Charddonany');
insert into products (id, name) values (666, 'Shrimp - Black Tiger 16/20');
insert into products (id, name) values (667, 'Icecream Cone - Areo Chocolate');
insert into products (id, name) values (668, 'Pepper - Green, Chili');
insert into products (id, name) values (669, 'Longos - Cheese Tortellini');
insert into products (id, name) values (670, 'Tomato - Peeled Italian Canned');
insert into products (id, name) values (671, 'Food Colouring - Green');
insert into products (id, name) values (672, 'Beef - Texas Style Burger');
insert into products (id, name) values (673, 'Eggroll');
insert into products (id, name) values (674, 'Nut - Pumpkin Seeds');
insert into products (id, name) values (675, 'Crab - Soft Shell');
insert into products (id, name) values (676, 'Lamb - Loin, Trimmed, Boneless');
insert into products (id, name) values (677, 'Turkey - Breast, Bone - In');
insert into products (id, name) values (678, 'Orange Roughy 4/6 Oz');
insert into products (id, name) values (679, 'Kellogs All Bran Bars');
insert into products (id, name) values (680, 'Arizona - Green Tea');
insert into products (id, name) values (681, 'Tuna - Sushi Grade');
insert into products (id, name) values (682, 'Wine - Vouvray Cuvee Domaine');
insert into products (id, name) values (683, 'Anchovy Fillets');
insert into products (id, name) values (684, 'Icecream - Dstk Cml And Fdg');
insert into products (id, name) values (685, 'Silicone Paper 16.5x24');
insert into products (id, name) values (686, 'Bread - Raisin Walnut Oval');
insert into products (id, name) values (687, 'Sea Urchin');
insert into products (id, name) values (688, 'Table Cloth 90x90 White');
insert into products (id, name) values (689, 'Flour Pastry Super Fine');
insert into products (id, name) values (690, 'Nori Sea Weed');
insert into products (id, name) values (691, 'Dill Weed - Dry');
insert into products (id, name) values (692, 'Pepper - Chilli Seeds Mild');
insert into products (id, name) values (693, 'Banana Turning');
insert into products (id, name) values (694, 'Wine - Mondavi Coastal Private');
insert into products (id, name) values (695, 'Turkey - Breast, Boneless Sk On');
insert into products (id, name) values (696, 'Wine - Red, Cabernet Merlot');
insert into products (id, name) values (697, 'Taro Leaves');
insert into products (id, name) values (698, 'Pork - Backfat');
insert into products (id, name) values (699, 'Bread - Pain Au Liat X12');
insert into products (id, name) values (700, 'Uniform Linen Charge');
insert into products (id, name) values (701, 'Wine - White, French Cross');
insert into products (id, name) values (702, 'Oranges - Navel, 72');
insert into products (id, name) values (703, 'Red Pepper Paste');
insert into products (id, name) values (704, 'Crab - Imitation Flakes');
insert into products (id, name) values (705, 'Pears - Fiorelle');
insert into products (id, name) values (706, 'Bread Ww Cluster');
insert into products (id, name) values (707, 'Pork - Ham, Virginia');
insert into products (id, name) values (708, 'Pastry - Cherry Danish - Mini');
insert into products (id, name) values (709, 'Wine - Sicilia Igt Nero Avola');
insert into products (id, name) values (710, 'Cake - French Pear Tart');
insert into products (id, name) values (711, 'Jello - Assorted');
insert into products (id, name) values (712, 'Red Snapper - Fillet, Skin On');
insert into products (id, name) values (713, 'Syrup - Monin - Blue Curacao');
insert into products (id, name) values (714, 'Salmon - Fillets');
insert into products (id, name) values (715, 'Shrimp - Black Tiger 16/20');
insert into products (id, name) values (716, 'Dates');
insert into products (id, name) values (717, 'Lamb - Racks, Frenched');
insert into products (id, name) values (718, 'Vodka - Moskovskaya');
insert into products (id, name) values (719, 'Juice - Cranberry 284ml');
insert into products (id, name) values (720, 'Beef - Ground, Extra Lean, Fresh');
insert into products (id, name) values (721, 'Plaintain');
insert into products (id, name) values (722, 'Rice Paper');
insert into products (id, name) values (723, 'Caviar - Salmon');
insert into products (id, name) values (724, 'Bread - Calabrese Baguette');
insert into products (id, name) values (725, 'Instant Coffee');
insert into products (id, name) values (726, 'Soup - French Can Pea');
insert into products (id, name) values (727, 'Pasta - Gnocchi, Potato');
insert into products (id, name) values (728, 'Grapes - Red');
insert into products (id, name) values (729, 'Langers - Mango Nectar');
insert into products (id, name) values (730, 'Cheese - Grie Des Champ');
insert into products (id, name) values (731, 'Raspberries - Fresh');
insert into products (id, name) values (732, 'Chicken - Whole');
insert into products (id, name) values (733, 'Corn - On The Cob');
insert into products (id, name) values (734, 'Muffin Chocolate Individual Wrap');
insert into products (id, name) values (735, 'Plate Foam Laminated 9in Blk');
insert into products (id, name) values (736, 'Longos - Grilled Salmon With Bbq');
insert into products (id, name) values (737, 'Soup - Campbells Chicken');
insert into products (id, name) values (738, 'Tart Shells - Sweet, 4');
insert into products (id, name) values (739, 'Basil - Fresh');
insert into products (id, name) values (740, 'Cheese - Grie Des Champ');
insert into products (id, name) values (741, 'Cheese - Gouda Smoked');
insert into products (id, name) values (742, 'Water - Evian 355 Ml');
insert into products (id, name) values (743, 'Ham - Proscuitto');
insert into products (id, name) values (744, 'Blouse / Shirt / Sweater');
insert into products (id, name) values (745, 'Pasta - Canelloni');
insert into products (id, name) values (746, 'Pork - Bacon, Sliced');
insert into products (id, name) values (747, 'Banana Turning');
insert into products (id, name) values (748, 'Soup - Campbells Mushroom');
insert into products (id, name) values (749, 'Wine - Vineland Estate Semi - Dry');
insert into products (id, name) values (750, 'Soup Knorr Chili With Beans');
insert into products (id, name) values (751, 'Sage - Ground');
insert into products (id, name) values (752, 'Cookie - Dough Variety');
insert into products (id, name) values (753, 'Iced Tea Concentrate');
insert into products (id, name) values (754, 'Rambutan');
insert into products (id, name) values (755, 'Bag - Bread, White, Plain');
insert into products (id, name) values (756, 'Vanilla Beans');
insert into products (id, name) values (757, 'Sauce - Apple, Unsweetened');
insert into products (id, name) values (758, 'Coffee - Dark Roast');
insert into products (id, name) values (759, 'Melon - Watermelon Yellow');
insert into products (id, name) values (760, 'Pepper - Red, Finger Hot');
insert into products (id, name) values (761, 'Muffin - Banana Nut Individual');
insert into products (id, name) values (762, 'Bread - French Stick');
insert into products (id, name) values (763, 'Soup - Tomato Mush. Florentine');
insert into products (id, name) values (764, 'Rappini - Andy Boy');
insert into products (id, name) values (765, 'Wine - Chianti Classico Riserva');
insert into products (id, name) values (766, 'Ice Cream - Strawberry');
insert into products (id, name) values (767, 'Pepsi - 600ml');
insert into products (id, name) values (768, 'Gooseberry');
insert into products (id, name) values (769, 'Bagels Poppyseed');
insert into products (id, name) values (770, 'Bread - Pain Au Liat X12');
insert into products (id, name) values (771, 'Sprouts Dikon');
insert into products (id, name) values (772, 'Wine - Vineland Estate Semi - Dry');
insert into products (id, name) values (773, 'Lobster - Baby, Boiled');
insert into products (id, name) values (774, 'Wheat - Soft Kernal Of Wheat');
insert into products (id, name) values (775, 'Garbage Bags - Black');
insert into products (id, name) values (776, 'Cocoa Feuilletine');
insert into products (id, name) values (777, 'Dried Apple');
insert into products (id, name) values (778, 'Cheese - Parmesan Grated');
insert into products (id, name) values (779, 'Butter - Pod');
insert into products (id, name) values (780, 'Easy Off Oven Cleaner');
insert into products (id, name) values (781, 'Mayonnaise');
insert into products (id, name) values (782, 'Pork - Back, Long Cut, Boneless');
insert into products (id, name) values (783, 'Cheese - Gorgonzola');
insert into products (id, name) values (784, 'Pie Pecan');
insert into products (id, name) values (785, 'Sesame Seed');
insert into products (id, name) values (786, 'Nut - Hazelnut, Whole');
insert into products (id, name) values (787, 'Macaroons - Two Bite Choc');
insert into products (id, name) values (788, 'Cheese - Mozzarella, Buffalo');
insert into products (id, name) values (789, 'Muskox - French Rack');
insert into products (id, name) values (790, 'Zucchini - Yellow');
insert into products (id, name) values (791, 'Easy Off Oven Cleaner');
insert into products (id, name) values (792, 'Chick Peas - Canned');
insert into products (id, name) values (793, 'Salad Dressing');
insert into products (id, name) values (794, 'Juice - Cranberry, 341 Ml');
insert into products (id, name) values (795, 'Cookie - Dough Variety');
insert into products (id, name) values (796, 'Swordfish Loin Portions');
insert into products (id, name) values (797, 'Potatoes - Yukon Gold 5 Oz');
insert into products (id, name) values (798, 'Coconut - Shredded, Unsweet');
insert into products (id, name) values (799, 'Soup Campbells');
insert into products (id, name) values (800, 'Pork - Belly Fresh');
insert into products (id, name) values (801, 'Muffin - Zero Transfat');
insert into products (id, name) values (802, 'Nantucket - Carrot Orange');
insert into products (id, name) values (803, 'Pork - Smoked Back Bacon');
insert into products (id, name) values (804, 'Milk - 1%');
insert into products (id, name) values (805, 'Scotch - Queen Anne');
insert into products (id, name) values (806, 'Chips - Miss Vickies');
insert into products (id, name) values (807, 'Cookie Double Choco');
insert into products (id, name) values (808, 'Apple - Granny Smith');
insert into products (id, name) values (809, 'Flavouring Vanilla Artificial');
insert into products (id, name) values (810, 'Foil - Round Foil');
insert into products (id, name) values (811, 'Black Currants');
insert into products (id, name) values (812, 'Sauce - Soya, Light');
insert into products (id, name) values (813, 'Coffee - Hazelnut Cream');
insert into products (id, name) values (814, 'Ocean Spray - Ruby Red');
insert into products (id, name) values (815, 'Beets');
insert into products (id, name) values (816, 'Foam Tray S2');
insert into products (id, name) values (817, 'Energy Drink - Franks Pineapple');
insert into products (id, name) values (818, 'Godiva White Chocolate');
insert into products (id, name) values (819, 'Sherbet - Raspberry');
insert into products (id, name) values (820, 'Fennel');
insert into products (id, name) values (821, 'Table Cloth 144x90 White');
insert into products (id, name) values (822, 'Worcestershire Sauce');
insert into products (id, name) values (823, 'Glass Clear 8 Oz');
insert into products (id, name) values (824, 'Mousse - Passion Fruit');
insert into products (id, name) values (825, 'Tomatoes - Roma');
insert into products (id, name) values (826, 'Sage Derby');
insert into products (id, name) values (827, 'Glucose');
insert into products (id, name) values (828, 'Coffee - Decafenated');
insert into products (id, name) values (829, 'Chicken - Tenderloin');
insert into products (id, name) values (830, 'Corn Meal');
insert into products (id, name) values (831, 'Fruit Mix - Light');
insert into products (id, name) values (832, 'Crab Brie In Phyllo');
insert into products (id, name) values (833, 'Sole - Dover, Whole, Fresh');
insert into products (id, name) values (834, 'Bay Leaf');
insert into products (id, name) values (835, 'Wine - Zonnebloem Pinotage');
insert into products (id, name) values (836, 'Soup - Campbells Beef Noodle');
insert into products (id, name) values (837, 'Wiberg Super Cure');
insert into products (id, name) values (838, 'Wine - Chateau Bonnet');
insert into products (id, name) values (839, 'Pastry - Lemon Danish - Mini');
insert into products (id, name) values (840, 'Chick Peas - Dried');
insert into products (id, name) values (841, 'Ice Cream Bar - Rolo Cone');
insert into products (id, name) values (842, 'Jicama');
insert into products (id, name) values (843, 'Skirt - 24 Foot');
insert into products (id, name) values (844, 'Sprite - 355 Ml');
insert into products (id, name) values (845, 'Muffin Mix - Chocolate Chip');
insert into products (id, name) values (846, 'Cheese - Mix');
insert into products (id, name) values (847, 'Seedlings - Buckwheat, Organic');
insert into products (id, name) values (848, 'Spic And Span All Purpose');
insert into products (id, name) values (849, 'Carrots - Mini, Stem On');
insert into products (id, name) values (850, 'Cheese - Cheddar With Claret');
insert into products (id, name) values (851, 'Cheese - Mix');
insert into products (id, name) values (852, 'Yoplait Drink');
insert into products (id, name) values (853, 'Beans - Yellow');
insert into products (id, name) values (854, 'Beef Wellington');
insert into products (id, name) values (855, 'Wine - Blue Nun Qualitatswein');
insert into products (id, name) values (856, 'Green Scrubbie Pad H.duty');
insert into products (id, name) values (857, 'Artichokes - Jerusalem');
insert into products (id, name) values (858, 'Jam - Apricot');
insert into products (id, name) values (859, 'Sping Loaded Cup Dispenser');
insert into products (id, name) values (860, 'Jagermeister');
insert into products (id, name) values (861, 'Pastry - Banana Tea Loaf');
insert into products (id, name) values (862, 'Wine - Tribal Sauvignon');
insert into products (id, name) values (863, 'Table Cloth 54x54 White');
insert into products (id, name) values (864, 'Rice - Sushi');
insert into products (id, name) values (865, 'Nut - Hazelnut, Whole');
insert into products (id, name) values (866, 'Rappini - Andy Boy');
insert into products (id, name) values (867, 'Wine - Red, Antinori Santa');
insert into products (id, name) values (868, 'Wine - Two Oceans Cabernet');
insert into products (id, name) values (869, 'Bar Mix - Lime');
insert into products (id, name) values (870, 'Cod - Salted, Boneless');
insert into products (id, name) values (871, 'Bread - Onion Focaccia');
insert into products (id, name) values (872, 'Sardines');
insert into products (id, name) values (873, 'Wine - White, Ej Gallo');
insert into products (id, name) values (874, 'Dried Cranberries');
insert into products (id, name) values (875, 'Danishes - Mini Cheese');
insert into products (id, name) values (876, 'Mahi Mahi');
insert into products (id, name) values (877, 'Temperature Recording Station');
insert into products (id, name) values (878, 'Initation Crab Meat');
insert into products (id, name) values (879, 'Toothpick Frilled');
insert into products (id, name) values (880, 'Chick Peas - Dried');
insert into products (id, name) values (881, 'Bar Bran Honey Nut');
insert into products (id, name) values (882, 'Bagel - Sesame Seed Presliced');
insert into products (id, name) values (883, 'Lady Fingers');
insert into products (id, name) values (884, 'Shrimp - Tiger 21/25');
insert into products (id, name) values (885, 'Mushroom - Enoki, Dry');
insert into products (id, name) values (886, 'Canadian Emmenthal');
insert into products (id, name) values (887, 'Crab - Meat');
insert into products (id, name) values (888, 'Raisin - Golden');
insert into products (id, name) values (889, 'Lid - 0090 Clear');
insert into products (id, name) values (890, 'Daves Island Stinger');
insert into products (id, name) values (891, 'Long Island Ice Tea');
insert into products (id, name) values (892, 'Soup - Campbells, Beef Barley');
insert into products (id, name) values (893, 'Bread - Italian Corn Meal Poly');
insert into products (id, name) values (894, 'Truffle Cups - Brown');
insert into products (id, name) values (895, 'Ice Cream - Fudge Bars');
insert into products (id, name) values (896, 'Beef - Tongue, Cooked');
insert into products (id, name) values (897, 'Wine - Bourgogne 2002, La');
insert into products (id, name) values (898, 'Beef - Ox Tongue, Pickled');
insert into products (id, name) values (899, 'Beef - Short Ribs');
insert into products (id, name) values (900, 'Carbonated Water - Blackcherry');
insert into products (id, name) values (901, 'Apple - Northern Spy');
insert into products (id, name) values (902, 'Mushroom - Lg - Cello');
insert into products (id, name) values (903, 'Water - Green Tea Refresher');
insert into products (id, name) values (904, 'Coffee - Frthy Coffee Crisp');
insert into products (id, name) values (905, 'Duck - Legs');
insert into products (id, name) values (906, 'Macaroons - Two Bite Choc');
insert into products (id, name) values (907, 'Chips Potato Salt Vinegar 43g');
insert into products (id, name) values (908, 'Cucumber - Pickling Ontario');
insert into products (id, name) values (909, 'Beer - Sleemans Honey Brown');
insert into products (id, name) values (910, 'Carbonated Water - Lemon Lime');
insert into products (id, name) values (911, 'Bread - Pita, Mini');
insert into products (id, name) values (912, 'Sugar Thermometer');
insert into products (id, name) values (913, 'Cheese - Marble');
insert into products (id, name) values (914, 'Sauce Tomato Pouch');
insert into products (id, name) values (915, 'Thyme - Lemon, Fresh');
insert into products (id, name) values (916, 'Honey - Comb');
insert into products (id, name) values (917, 'Lidsoupcont Rp12dn');
insert into products (id, name) values (918, 'Salmon Atl.whole 8 - 10 Lb');
insert into products (id, name) values (919, 'Bacardi Raspberry');
insert into products (id, name) values (920, 'Chicken - Whole Roasting');
insert into products (id, name) values (921, 'Potatoes - Mini White 3 Oz');
insert into products (id, name) values (922, 'Coffee Caramel Biscotti');
insert into products (id, name) values (923, 'Bacardi Limon');
insert into products (id, name) values (924, 'Napkin White');
insert into products (id, name) values (925, 'Wine - White, Concha Y Toro');
insert into products (id, name) values (926, 'Spinach - Packaged');
insert into products (id, name) values (927, 'Bread - Bagels, Plain');
insert into products (id, name) values (928, 'Dried Figs');
insert into products (id, name) values (929, 'Bread - Bistro Sour');
insert into products (id, name) values (930, 'Yokaline');
insert into products (id, name) values (931, 'Crab - Claws, Snow 16 - 24');
insert into products (id, name) values (932, 'Cup Translucent 9 Oz');
insert into products (id, name) values (933, 'Potatoes - Peeled');
insert into products (id, name) values (934, 'Country Roll');
insert into products (id, name) values (935, 'Wine - Red, Black Opal Shiraz');
insert into products (id, name) values (936, 'Soup Campbells Split Pea And Ham');
insert into products (id, name) values (937, 'Brandy Cherry - Mcguinness');
insert into products (id, name) values (938, 'Salmon - Whole, 4 - 6 Pounds');
insert into products (id, name) values (939, 'Mushroom - Oyster, Fresh');
insert into products (id, name) values (940, 'Fennel');
insert into products (id, name) values (941, 'Onions Granulated');
insert into products (id, name) values (942, 'Lychee');
insert into products (id, name) values (943, 'Steam Pan Full Lid');
insert into products (id, name) values (944, 'Pasta - Lasagne, Fresh');
insert into products (id, name) values (945, 'Soup - Campbells Broccoli');
insert into products (id, name) values (946, 'Skewers - Bamboo');
insert into products (id, name) values (947, 'Cake - Cake Sheet Macaroon');
insert into products (id, name) values (948, 'Muffin Mix - Corn Harvest');
insert into products (id, name) values (949, 'Soupcontfoam16oz 116con');
insert into products (id, name) values (950, 'Allspice - Jamaican');
insert into products (id, name) values (951, 'Glass - Juice Clear 5oz 55005');
insert into products (id, name) values (952, 'Squid U5 - Thailand');
insert into products (id, name) values (953, 'Wine - Sauvignon Blanc Oyster');
insert into products (id, name) values (954, 'Salmon Atl.whole 8 - 10 Lb');
insert into products (id, name) values (955, 'Pate - Cognac');
insert into products (id, name) values (956, 'Cookies - Englishbay Oatmeal');
insert into products (id, name) values (957, 'Syrup - Pancake');
insert into products (id, name) values (958, 'Curry Paste - Madras');
insert into products (id, name) values (959, 'Tea - Herbal Orange Spice');
insert into products (id, name) values (960, 'Cookie Double Choco');
insert into products (id, name) values (961, 'Chilli Paste, Ginger Garlic');
insert into products (id, name) values (962, 'Bread - Olive');
insert into products (id, name) values (963, 'Cheese - Manchego, Spanish');
insert into products (id, name) values (964, 'White Fish - Filets');
insert into products (id, name) values (965, 'Swordfish Loin Portions');
insert into products (id, name) values (966, 'Fish - Scallops, Cold Smoked');
insert into products (id, name) values (967, 'Juice - Prune');
insert into products (id, name) values (968, 'Onions - Dried, Chopped');
insert into products (id, name) values (969, 'Canadian Emmenthal');
insert into products (id, name) values (970, 'Jam - Strawberry, 20 Ml Jar');
insert into products (id, name) values (971, 'Lid - 16 Oz And 32 Oz');
insert into products (id, name) values (972, 'Salmon - Atlantic, Fresh, Whole');
insert into products (id, name) values (973, 'Blackberries');
insert into products (id, name) values (974, 'Muffin Orange Individual');
insert into products (id, name) values (975, 'Paper - Brown Paper Mini Cups');
insert into products (id, name) values (976, 'Cookies - Englishbay Wht');
insert into products (id, name) values (977, 'Soap - Hand Soap');
insert into products (id, name) values (978, 'Bread - Sour Batard');
insert into products (id, name) values (979, 'Veal - Insides Provini');
insert into products (id, name) values (980, 'Pepper - Cayenne');
insert into products (id, name) values (981, 'Wine - Chardonnay Mondavi');
insert into products (id, name) values (982, 'Veal - Knuckle');
insert into products (id, name) values (983, 'Pork - Back Ribs');
insert into products (id, name) values (984, 'Water - Spring Water, 355 Ml');
insert into products (id, name) values (985, 'Saskatoon Berries - Frozen');
insert into products (id, name) values (986, 'Smoked Tongue');
insert into products (id, name) values (987, 'Pail For Lid 1537');
insert into products (id, name) values (988, 'Filling - Mince Meat');
insert into products (id, name) values (989, 'Beets - Golden');
insert into products (id, name) values (990, 'Beef - Baby, Liver');
insert into products (id, name) values (991, 'Remy Red');
insert into products (id, name) values (992, 'Pastry - Baked Cinnamon Stick');
insert into products (id, name) values (993, 'Veal - Knuckle');
insert into products (id, name) values (994, 'Carbonated Water - Blackcherry');
insert into products (id, name) values (995, 'Beef Dry Aged Tenderloin Aaa');
insert into products (id, name) values (996, 'Veal - Brisket, Provimi, Bone - In');
insert into products (id, name) values (997, 'Maintenance Removal Charge');
insert into products (id, name) values (998, 'Salmon Steak - Cohoe 8 Oz');
insert into products (id, name) values (999, 'Shrimp, Dried, Small / Lb');
insert into products (id, name) values (1000, 'Sword Pick Asst');
