global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flask_api:8080']

  - job_name: 'anomaly_worker'  # <-- Agregamos el nuevo servicio
    metrics_path: '/metrics'
    static_configs:
      - targets: ['anomaly_worker:8001']